# Name: Makefile.windows
# Project: usbtool
# Author: Christian Starkjohann
# Creation Date: 2008-04-06
# Tabsize: 4
# Copyright: (c) 2008 by OBJECTIVE DEVELOPMENT Software GmbH
# License: GNU GPL v2 (see License.txt), GNU GPL v3 or proprietary (CommercialLicense.txt)

# You may use this file with
#   make -f Makefile.windows
# on Windows with MinGW instead of editing the main Makefile.

include Makefile

USBFLAGS = -I/include
USBLIBS = -L/lib -lusb
EXE_SUFFIX = .exe
